### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ForceTK** [G3VEZE/gvz-anticheat#3]
when i start the script i get this problem

![unknown](https://user-images.githubusercontent.com/82717556/115158248-e788b700-a095-11eb-96b2-ae54220f011e.png)

![image](https://user-images.githubusercontent.com/82717556/115158284-14d56500-a096-11eb-8bdf-fda1c207018c.png)

**Comment by G3VEZE** [comment]
You downloaded the first version, yes there was such a problem, but now the repositories is up to date and without any problems :)

**Comment by ForceTK** [comment]
oh okay my problem is solved thanks.
