### ISSUE TITLE
Remove the spawned ped or vehicle after kicking the cheater

### ISSUE THREAD

**Issue by zoomlordir** [G3VEZE/gvz-anticheat#5]
is it possible to remove peds or vehicles spawned by cheater?

**Comment by G3VEZE** [comment]
yes possible, you can make adjustments from config.lua.

**Comment by zoomlordir** [comment]
sry i mean delete the vehicle after spawn 
like cheater spawn a tank and other players can use it

**Comment by G3VEZE** [comment]
You can edit it from config.lua as you wish

**Comment by zoomlordir** [comment]
sry which part i cant find it

**Comment by G3VEZE** [comment]
![image](https://user-images.githubusercontent.com/74410669/115864027-faf1a480-a43e-11eb-8fb7-783550e97d68.png)


![image](https://user-images.githubusercontent.com/74410669/115864115-1eb4ea80-a43f-11eb-9635-98daf42a3f14.png)


If you want the game to kick the cheat vehicle when you release it, you have to turn it on.

**Comment by zoomlordir** [comment]
yea i know this but when game kick the cheater the vehicle still there i want to remove that vehicle after kick the cheater

**Comment by G3VEZE** [comment]
There is no such feature now, but I can do it in the future.

**Comment by zoomlordir** [comment]
It will be really great **thank you**
